
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/bionic64"

  # For resize needs vagrant-disksize plugin: vagrant plugin install vagrant-disksize
  # May need resize inside the VM with Gparted, because the extra space is unused
  config.disksize.size = '240GB' 

  # create a shared folder for the top-level project directory at /vagrant
  # normally already configured but for some reason it isn't on some boxes
  # https://www.vagrantup.com/docs/synced-folders/virtualbox.html#automount
  # http://www.virtualbox.org/manual/ch04.html#sf_mount_auto
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", automount: true

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider :virtualbox do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.name = "bionic64"
    vb.check_guest_additions = true

    vb.memory = 16384
    vb.cpus = 4

    vb.customize ["modifyvm", :id, "--vram", "64"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end

  config.vm.provision "shell", name: "install-basic-dependencies", privileged: false, path: "provision.sh"
end
